version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    rebase-strategy: disabled
    assignees:
      - DCjanus

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      patch-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - patch
    rebase-strategy: disabled
    assignees:
      - DCjanus
