version: "3.8"

name: rdbinsight-dev

services:
  redis:
    image: redis:8-alpine
    ports:
      - "6380:6379" # Host port 6380 -> Container port 6379
    command: redis-server --appendonly no --save "" --maxmemory 256mb --maxmemory-policy allkeys-lru --repl-diskless-sync-delay 0
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 10
      start_period: 5s
    networks:
      - rdbinsight-dev

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8124:8123" # HTTP interface: Host port 8124 -> Container port 8123
      - "9001:9000" # Native client: Host port 9001 -> Container port 9000
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_USER: rdbinsight
      CLICKHOUSE_PASSWORD: rdbinsight
      CLICKHOUSE_DB: rdbinsight
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "clickhouse-client", "--user=rdbinsight", "--password=rdbinsight", "--query=SELECT 1"]
      interval: 1s
      timeout: 5s
      retries: 15
      start_period: 15s
    networks:
      - rdbinsight-dev

networks:
  rdbinsight-dev:
    driver: bridge
