concurrency = 1

[source]
type = "redis_standalone"
cluster_name = "dev-test-cluster"
address = "127.0.0.1:6380"
# No username/password needed for Redis in dev environment

[output]
type = "clickhouse"
address = "http://127.0.0.1:8124"
username = "rdbinsight"
password = "rdbinsight"
database = "rdbinsight"
auto_create_tables = true
