concurrency = 10

[source]
type = "redis_cluster"
cluster_name = "my-cluster"
batch_id = "batch-123"
instances = ["127.0.0.1:6379", "127.0.0.1:6380", "127.0.0.1:6381"]
username = "default"
password = "123456"

[output]
type = "clickhouse"
address = "127.0.0.1:9000"
username = "default"
password = "123456" 