concurrency = 8

[source]
type = "codis"
dashboard_addr = "http://127.0.0.1:11080"
password = "your_redis_password"

[output]
type = "clickhouse"
address = "http://127.0.0.1:8124"
username = "rdbinsight"
password = "rdbinsight"
database = "rdbinsight"
auto_create_tables = true  # Set to true to automatically create tables if they don't exist
