concurrency = 10

[source]
type = "redis_standalone"
cluster_name = "my-standalone-cluster"
address = "127.0.0.1:6379"
username = "default"
password = "123456"

[output]
type = "clickhouse"
address = "127.0.0.1:9000"
username = "default"
password = "123456"
# auto_create_tables = true  # Set to true to automatically create tables if they don't exist
