concurrency = 10

[source]
type = "redis_standalone"
cluster_name = "my-standalone-cluster"
address = "127.0.0.1:6379"
username = "default"
password = "123456"

[output]
type = "clickhouse"
address = "http://127.0.0.1:8124"
username = "rdbinsight"
password = "rdbinsight"
database = "rdbinsight"
auto_create_tables = true  # Set to true to automatically create tables if they don't exist 
