concurrency = 10

[source]
type = "redis_sentinel"
cluster_name = "my-sentinel-cluster"
master_name = "mymaster"
sentinels = ["127.0.0.1:26379", "127.0.0.1:26380", "127.0.0.1:26381"]
username = "default"
password = "123456"

[output]
type = "clickhouse"
address = "127.0.0.1:9000"
username = "default"
password = "123456" 