name: CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check (fmt + clippy + tests)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install nightly Rust toolchain (rustfmt + llvm-tools-preview)
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, llvm-tools-preview, clippy

      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest

      - name: Cache target directory
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Run cargo fmt --check (nightly)
        run: cargo +nightly fmt --all -- --check

      - name: Run cargo clippy (nightly)
        run: cargo +nightly clippy --all -- -D warnings

      - name: Generate coverage report (cargo llvm-cov + nextest)
        run: |
          CARGO_LLVM_COV_SETUP=yes \
          cargo +nightly llvm-cov nextest \
            --all-features --workspace \
            --branch --codecov --output-path codecov.json

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          files: codecov.json
          fail_ci_if_error: true

  docker-builds:
    name: Docker Build (${{ matrix.name }})
    needs: [check]
    if: ${{ github.event_name != 'pull_request' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: amd64
            platform: linux/amd64
            runs-on: ubuntu-latest
          - name: arm64
            platform: linux/arm64
            runs-on: ubuntu-24.04-arm
    runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute image name (lowercase)
        id: vars
        shell: bash
        run: |
          echo "image=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.vars.outputs.image }}

      - name: Build and push (${{ matrix.platform }})
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ steps.vars.outputs.image }},push-by-digest=true,push=true

      - name: Persist image digest
        run: |
          echo "PLATFORM=${{ matrix.platform }}" > digest.env
          echo "DIGEST=${{ steps.build.outputs.digest }}" >> digest.env
        shell: bash

      - name: Upload digest artifact
        uses: actions/upload-artifact@v4
        with:
          name: digest-${{ matrix.name }}
          path: digest.env

  docker-merge:
    name: Docker push
    runs-on: ubuntu-latest
    needs: [docker-builds]
    if: ${{ github.event_name != 'pull_request' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute image name (lowercase)
        id: vars
        shell: bash
        run: |
          echo "image=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"

      - name: Download digest (amd64)
        uses: actions/download-artifact@v4
        with:
          name: digest-amd64
          path: digests/amd64

      - name: Download digest (arm64)
        uses: actions/download-artifact@v4
        with:
          name: digest-arm64
          path: digests/arm64

      - name: Docker metadata (recompute tags)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.vars.outputs.image }}
          flavor: |
            latest=false
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Create and push multi-arch manifest
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          set -euo pipefail
          IMAGE="ghcr.io/${GITHUB_REPOSITORY,,}"
          source digests/amd64/digest.env
          AMD_DIGEST="$DIGEST"
          source digests/arm64/digest.env
          ARM_DIGEST="$DIGEST"
          # docker/metadata-action returns newline-separated tags
          while IFS= read -r tag; do
            if [ -n "$tag" ]; then
              echo "Merging $tag with $IMAGE@${AMD_DIGEST} and $IMAGE@${ARM_DIGEST}"
              docker buildx imagetools create -t "$tag" \
                "$IMAGE@${AMD_DIGEST}" \
                "$IMAGE@${ARM_DIGEST}"
            fi
          done <<< "$TAGS"


