# NOTE: This workflow is triggered on pushes to the master branch only.
# TODO: Once the repository is open-sourced and GitHub Actions & Codecov are free,
#       enable triggering on pull_request events so that coverage runs for every PR.

name: Coverage

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install stable Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install nightly Rust toolchain (llvm-tools-preview)
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools-preview

      - name: Cache Cargo registry + index
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache target directory
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest

      - name: Generate coverage report (cargo llvm-cov + nextest)
        run: |
          CARGO_LLVM_COV_SETUP=yes \
          cargo +nightly llvm-cov nextest \
            --all-features --workspace \
            --branch --codecov --output-path codecov.json

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          files: codecov.json
          fail_ci_if_error: true
