name: GHCR Cleanup

on:
  schedule:
    - cron: "42 0 * * *" # clean up ghcr images every day at 00:42 UTC
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up GHCR (delete only untagged, dependency-aware)
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          delete-untagged: true
