name: GHCR Cleanup

on:
  schedule:
    - cron: "42 0 * * *" # clean up ghcr images every day at 00:42 UTC
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete truly untagged GHCR images (dependency-safe)
        uses: quartx-analytics/ghcr-cleaner@v1
        with:
          owner-type: user
          token: ${{ secrets.GITHUB_TOKEN }}
          package-name: ${{ github.event.repository.name }}
